### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by Mte90** [strangerstudios/pmpro-better-logins-report#1]
The users list generated by this plugin is unuseful without a sorting!
I've see the code and add this feature is very difficult but use the Wp_List_Table i think that is a better solution http://www.sitepoint.com/using-wp_list_table-to-create-wordpress-admin-tables/ that have sortable support natively.

**Comment by Mte90** [comment]
@strangerstudios there any news about that?

**Comment by strangerstudios** [comment]
> The users list generated by this plugin...

Do you mean in the main plugin or just in the better logins?

> there any news about that?

Thanks for the link to the WP_List_Table class. Now immediately plans for us to overhaul this. If you're up to doing the work, I'll be happy to accept the pull request or answer specific questions about implementing it.

**Comment by strangerstudios** [comment]
Note that overhauling things to use WP List Table might help a bit, but would also require us to figure out how to support plugins/etc already using the header/body hooks we have in the current system. Also, we'd still have to program the sorting logic and query updates for sorting.

So I don't think switching to WP List Table will save much time. If someone is interested in working on sorting for columns, let me know and I'll lay out how I would go about it.

**Comment by Mte90** [comment]
The question is that the list of user generated from this plugin is useless without sorting. 
Use Wp List table is not the only solution but the important is add the sorting, for the pr actually i've no time to work on it :-/
